/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORT_H_RPCGEN
#define _AIRPORT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXLEN 255

typedef char *nametype_air;
    /*
     Airport node to contain name, airport code, latitude, longitude
     and distance and the next airport node
     */
struct airportNode {
	nametype_air airportName;
	nametype_air airportCode;
	double latitude;
	double longitude;
	double distance;
	struct airportNode *next;
};
typedef struct airportNode airportNode;

    /*
     city node to just hold city latitude and longitude to search for nearest airports
     */
struct cityNode {
	double cityLat;
	double cityLong;
};
typedef struct cityNode cityNode;
    /*
     return value of nearest airports, returns airport node list of nearest airports
     */
struct nearestAiports_ret {
	int err;
	union {
		airportNode *list;
	} nearestAiports_ret_u;
};
typedef struct nearestAiports_ret nearestAiports_ret;

#define AIRPORT_PROG 0x31331332
#define AIRPORT_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FINDAIRPORT 1
extern  nearestAiports_ret * findairport_1(cityNode *, CLIENT *);
extern  nearestAiports_ret * findairport_1_svc(cityNode *, struct svc_req *);
extern int airport_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FINDAIRPORT 1
extern  nearestAiports_ret * findairport_1();
extern  nearestAiports_ret * findairport_1_svc();
extern int airport_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_nametype_air (XDR *, nametype_air*);
extern  bool_t xdr_airportNode (XDR *, airportNode*);
extern  bool_t xdr_cityNode (XDR *, cityNode*);
extern  bool_t xdr_nearestAiports_ret (XDR *, nearestAiports_ret*);

#else /* K&R C */
extern bool_t xdr_nametype_air ();
extern bool_t xdr_airportNode ();
extern bool_t xdr_cityNode ();
extern bool_t xdr_nearestAiports_ret ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORT_H_RPCGEN */
