/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "airport.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

nearestAiports_ret *
findairport_1(cityNode *argp, CLIENT *clnt)
{
	static nearestAiports_ret clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call (clnt, FINDAIRPORT,
		(xdrproc_t) xdr_cityNode, (caddr_t) argp,
		(xdrproc_t) xdr_nearestAiports_ret, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
