/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "airport.h"

bool_t
xdr_nametype_air (XDR *xdrs, nametype_air *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_airportNode (XDR *xdrs, airportNode *objp)
{
	register int32_t *buf;

	 if (!xdr_nametype_air (xdrs, &objp->airportName))
		 return FALSE;
	 if (!xdr_nametype_air (xdrs, &objp->airportCode))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (airportNode), (xdrproc_t) xdr_airportNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cityNode (XDR *xdrs, cityNode *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->cityLat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->cityLong))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nearestAiports_ret (XDR *xdrs, nearestAiports_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->nearestAiports_ret_u.list, sizeof (airportNode), (xdrproc_t) xdr_airportNode))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
