/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_nametype (XDR *xdrs, nametype *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_locationNode (XDR *xdrs, locationNode *objp)
{
	register int32_t *buf;

	 if (!xdr_nametype (xdrs, &objp->airportName))
		 return FALSE;
	 if (!xdr_nametype (xdrs, &objp->airportCode))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->cityLat))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->cityLong))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->head, sizeof (locationNode), (xdrproc_t) xdr_locationNode))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_stateNode (XDR *xdrs, stateNode *objp)
{
	register int32_t *buf;

	 if (!xdr_nametype (xdrs, &objp->city))
		 return FALSE;
	 if (!xdr_nametype (xdrs, &objp->state))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_nearestPlace_ret (XDR *xdrs, nearestPlace_ret *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->err))
		 return FALSE;
	switch (objp->err) {
	case 0:
		 if (!xdr_pointer (xdrs, (char **)&objp->nearestPlace_ret_u.list, sizeof (locationNode), (xdrproc_t) xdr_locationNode))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
